apiVersion: appshare.appshare.co/v1
kind: AppShare
metadata:
  name: appshare-sample
spec:
  # Add fields here
  replicas: 1
  resources: 
    limits: 
      cpu: 4000m
      memory: 4096Mi
    requests:
      cpu: 500m
      memory: 512Mi
